import { defineStore } from 'pinia'

export default function elementStores() {
    return defineStore('elements', {
        state: () => ({
            courses: [
                {
                    module: 'Module 1',
                    time: '4 Weeks',
                    field: 'Digital Literacy',
                    desc: "Embark on a journey of digital literacy with our comprehensive course. Develop a solid understanding of essential computer fundamentals and data processing concepts. Learn to navigate the digital landscape confidently, from mastering basic computer operations to exploring data manipulation techniques. Gain practical skills in utilizing software tools for efficient data processing, analysis, and presentation.",
                    image: '/others/digitalLiteracy.png',
                },
                {
                    module: 'Module 2',
                    time: '4 Weeks',
                    field: 'Scratch Programming',
                    desc: 'Dive into the world of coding through our beginner-friendly Scratch course. Build your foundational skills in logic, problem-solving, and creativity while developing projects with fun, visual programming blocks. Perfect for young learners and beginners eager to understand the fundamentals of programming in an engaging and playful way!',
                    image: '/others/scratch.webp',
                },
                {
                    module: 'Module 3',
                    time: '6 Weeks',
                    field: 'Web Development (Silver track)',
                    desc: 'Discover the fundamentals of web development in our introductory course. Learn HTML, CSS, and JavaScript essentials to build and style web pages. Acquire foundational skills for creating interactive and responsive websites. Perfect for beginners and those looking to grasp the basics of web development.',
                    image: '/others/webDevFund.png',
                },
                {
                    module: 'Module 4',
                    time: '4 weeks',
                    field: "Computer Hardware Engineering",
                    desc: "Learn the fundamentals of computer hardware engineering, focusing on the design, development, and maintenance of physical computer systems. Topics include processors, motherboards, memory, storage devices, power supplies, and peripheral devices. Build practical skills in assembling, troubleshooting, and upgrading computer hardware for optimal performance.",
                    image: "/others/computerEngineering.webp"
                },
                {
                    module: 'Module 5',
                    time: '4 Weeks(Weekend)',
                    field: 'Computer Networking Fundamentals',
                    desc: 'Dive into Computer Networking Fundamentals for beginners. Learn essential concepts of data transmission, network protocols, IP addressing, and network topologies. Acquire practical skills to set up, troubleshoot, and secure basic networks. Ideal for newcomers seeking a solid foundation in connecting and managing digital systems.',
                    image: '/others/computerNetworkingFundamentals.png',
                },
                {
                    module: 'Module 6',
                    time: '3 Weeks',
                    field: 'Web Design with CMS',
                    desc: 'Learn Web Design with CMS: Create stunning websites using Content Management Systems. Master layout design, UI/UX principles, and CMS integration. Build dynamic, responsive sites without coding. Perfect for beginners and designers looking to enhance skills in designing and managing websites efficiently.',
                    image: '/others/WebDesignWithCMS.png',
                },
                {
                    module: 'Module 7',
                    time: '3 days',
                    field: 'Website Management Training',
                    desc: 'Master the skills to manage and maintain websites efficiently. This course covers website hosting, domain management, content updates, security protocols, SEO optimization, and performance monitoring. Learn to handle technical aspects of a website and ensure a smooth user experience.',
                    image: '/others/websiteManagementTraining.jpg'
                },
                {
                    module: 'Module 8',
                    time: '2 Months',
                    field: 'UI / UX Designs',
                    desc: 'Master the art of UI/UX and software design in our comprehensive course. Learn design principles, wireframing, prototyping, and user-centered approaches. Gain hands-on experience creating visually stunning and user-friendly digital solutions. Perfect for aspiring designers and developers seeking to craft exceptional user experiences.',
                    image: '/others/uiUxSoftwareDesigns.png',
                },
                {
                    module: 'Module 9',
                    time: '12 Weeks',
                    field: 'Graphics Designs',
                    desc: 'Elevate your graphic design skills with our intermediate course. Delve into advanced techniques in typography, layout composition, image manipulation, and branding. Develop a diverse portfolio while honing your creative vision. Perfect for designers seeking to take their graphic design expertise to the next level.',
                    image: '/others/graphicsDesign.png',
                },
                {
                    module: 'Module 10',
                    time: '12 Weeks(Weekend)',
                    field: 'Data Analytics',
                    desc: 'Elevate your Excel skills in our intermediate-level course. Become a proficient Excel Power User through advanced functions, data manipulation, and visualization techniques. Uncover insights with data analysis tools, PivotTables, and charts. Ideal for individuals aiming to enhance their data handling...',
                    image: '/others/excelPowerUser.png',
                },
                {
                    module: 'Module 11',
                    time: '4 Weeks',
                    field: 'Excel Power User & Data Analysis',
                    desc: "Become an Excel power user by mastering advanced features such as pivot tables, macros, conditional formatting, and data visualization tools. Gain expertise in handling large datasets, performing complex calculations, and extracting insights through data analysis techniques that improve decision-making processes",
                    image: "/others/ExcelPowerUser-DataAnalysis.jpg"
                },
                {
                    module: 'Module 12',
                    time: '4 Weeks(Weekend)',
                    field: 'SPSS DATA ANALYSIS',
                    desc: 'Unlock the power of data analysis with our SPSS course. Learn to navigate, manipulate, and derive insights from data using IBM SPSS Statistics. Explore statistical techniques, hypothesis testing, and data visualization. Gain practical skills in data interpretation and decision-making. Ideal for beginners and professionals seeking to harness data for informed choices.',
                    image: '/others/spss.png',
                },
                {
                    module: 'Module 13',
                    time: '4 Weeks(Weekend)',
                    field: 'Digital Marketing & Social Media Enginering',
                    desc: 'Elevate your digital marketing prowess with our intermediate course. Dive into advanced strategies, analytics, and social media optimization. Harness the power of data-driven decisions and master effective online campaigns. Perfect for marketers aiming to deepen their skills in the dynamic landscape of digital marketing and social media engineering.',
                    image: '/others/digitalMarketing.png',
                },
                {
                    module: 'Module 14',
                    time: '4 Weeks(Weekend)',
                    field: 'Accounting and ERP Software',
                    desc: 'Delve into Accounting and ERP Software with our focused course. Acquire a comprehensive understanding of financial management, ledger systems, and enterprise resource planning. Develop practical skills in utilizing industry-leading software for efficient business operations. Ideal for those pursuing a career in finance and business management.',
                    image: '/others/AccountingAndERPSoftware.png',
                },
                {
                    module: 'Module 15',
                    time: '2 days',
                    field: 'Cyber Security Non-Technical',
                    desc: 'Dive into Advanced Cyber Security & Ethical Hacking with our intensive course. Explore cutting-edge techniques, threat analysis, and penetration testing. Develop expertise in securing networks, systems, and applications. Ideal for cybersecurity professionals aiming to elevate their skills in safeguarding digital environments and conducting ethical hacking assessments.',
                    image: '/others/cyberSecurity&EthicalHacking.png',
                },
                {
                    module: "Module 16",
                    time: "7 Weeks",
                    field: "Cybersecurity and Data Protection",
                    desc: "Acquire in-depth knowledge of cybersecurity practices, including encryption, firewalls, and access controls. Learn to protect networks, data, and systems from cyber threats by implementing secure protocols and understanding legal aspects of data protection. Perfect for anyone looking to secure digital environments",
                    image: "/others/Cybersecurity-DataProtection.jpg"
                },
                {
                    module: "Module 17",
                    time: "5 Weeks (Weekend)",
                    field: "Artificial Intelligence",
                    desc: "Explore the essentials of artificial intelligence, including machine learning, neural networks, natural language processing, and computer vision. Understand AI’s real-world applications in industries like healthcare, finance, and automation, and develop the skills to work with AI-powered systems",
                    image: "/others/artificialIntelligence.jpeg"
                },
                {
                    module: "Module 18",
                    time: "4 Weeks",
                    field: "Robotics Fundamentals",
                    desc: "Dive into the fascinating world of robotics, where you’ll learn about robotic design, control systems, sensors, and actuators. Gain practical experience in building and programming robots to perform tasks, with a focus on automation and engineering principles",
                    image: "/others/roboticsFundamentals.png"
                },
                {
                    module: "Module 19",
                    time: "4 Weeks(Weekend)",
                    field: "Video Editing",
                    desc: "ghhhhhhhhhhhhhhhhhh",
                    image: "/others/"
                },
                {
                    module: 'Module 20',
                    time: '4 Weeks(Weekend)',
                    field: 'Windows Server Administration & Management',
                    desc: 'Elevate Windows Server skills through our intermediate course. Master advanced administration, user management, group policies, security, and performance optimization. Ideal for IT professionals aiming to enhance Windows Server expertise and streamline organizational infrastructure for seamless network operations.',
                    image: '/others/windowsServerAdministration&Management.png',
                },
                {
                    module: 'Module 21',
                    time: '13 Weeks',
                    field: 'Front-End Development',
                    desc: 'Explore the core aspects of front-End web development in this hands-on course. Learn web design tools to create engaging and responsive user interfaces. Develop the skills to build and style web content, add interactivity, and ensure optimal user experiences across devices. Perfect for beginners and those looking to strengthen their front-End skills.',
                    image: '/others/frontEnd.png',
                },
                {
                    module: 'Module 22',
                    time: '16 Weeks',
                    field: 'Back-End Development',
                    desc: "Dive into the world of backend web development with our comprehensive course. Discover the backend's crucial role in powering web applications, databases, and server-side logic.Gain hands-on experience in building robust and scalable backend systems, making you proficient in delivering efficient and secure web solutions.",
                    image: '/others/backEnd.png' ,
                },
                {
                    module: 'Module 23',
                    time: '6 Months',
                    field: 'Full-stack Development',
                    desc: 'Discover the full range of web development in our Fullstack Web Development Mastery course. Seamlessly blend front-End and backend expertise to become a versatile developer creating holistic web solutions. Excel in Front-End tools for captivating interfaces, while exploring server-side technologies, APIs, databases, and security in depth.',
                    image: '/others/fullstack.png',
                },
                {
                    module: 'Module 24',
                    time: '8 Weeks',
                    field: 'Python Programming',
                    desc: 'Master Python Programming from basics to advanced levels in our comprehensive course. Learn syntax, data structures, algorithms, and object-oriented concepts. Explore web development, data analysis, and more. Build real-world projects and enhance your coding skills. Perfect for beginners and those looking to elevate their Python proficiency.',
                    image: '/others/pythonProgramming.png',
                },
                {
                    module: 'Module 25',
                    time: '12 Weeks',
                    field: 'Mobile App Development',
                    desc: 'Dive into Mobile App Development with our course. Learn to create responsive, feature-rich apps for iOS and Android. Master essential languages, frameworks, and design principles. Gain hands-on experience building functional and engaging mobile applications. Perfect for aspiring developers and those eager to innovate in the mobile app landscape.',
                    image: '/others/mobileAppDev.png',
                },
                {
                    module: 'Module 26',
                    time: '8 Weeks',
                    field: 'Java Programming',
                    desc: "Master Java programming essentials in our concise course. Learn syntax, data types, control structures, and object-oriented principles. Develop practical skills in creating applications and understanding Java's versatility. Perfect for beginners and those aiming to strengthen their Java proficiency for software development.",
                    image: '/others/javaProgramming.png',
                },
                {
                    module: 'Module 27',
                    time: '4 Weeks',
                    field: 'Linux Administration',
                    desc: 'Enhance your Linux admin skills with our intermediate course. Delve deeper into system management, networking, security, and scripting. Learn to configure, troubleshoot, and optimize Linux environments effectively. Ideal for those with basic Linux familiarity, aspiring to excel in diverse IT administration roles and responsibilities. Develop expertise for successful careers.',
                    image: '/others/linuxAdministration.png',
                },
                {
                    module: "Module 28",
                    time: "6 Weeks",
                    field: "Red Hat System Administration",
                    desc: "lllllllllllllllllllllll",
                    image: "/others/"
                },
                {
                    module: 'Module 29',
                    time: '8 Weeks(Weekend)',
                    field: 'Virtualization Technology',
                    desc: 'Dive deep into Advanced Virtualization Technology with our course. Explore cutting-edge techniques in virtualization, containerization, and cloud computing. Develop expertise in optimizing resource utilization, scalability, and infrastructure management. Ideal for tech professionals looking to elevate their virtualization skills and drive efficient IT solutions.',
                    image: '/others/virtualizationTechnology.png',
                },
                {
                    module: "Module 30",
                    time: "7 Weeks",
                    field: "DevOps Engineering",
                    desc: "mmmmmmmmmmmmmmmmm",
                    image: "/others/"
                },
            ],
            testifier: 0,
            testimonials: [
                {
                    name: 'Zakariyyah Okeyale ',
                    occupation: 'Front-End Dev.',
                    speech: 'I had an incredible experience at Dervac Hub!  The comprehensive curriculum, hands-on projects and knowledgeable instructors made learning complex concepts a breeze. The practical approach to teaching ensured that I not only understood the theory but could also apply it in real-world scenarios. Am excited about the opportunities ahead. I highly recommend Dervac Hub to anyone looking to kickstart or enhance their career in technology.',
                    image: '/alfa-Zakariyyah.jpg'
                },
                {
                    name: 'Hammed Sanni',
                    occupation: 'Front-End Dev.',
                    speech: 'At Dervac, we believe that everyone deserves the opportunity to pursue their dreams without the burden of the debt. Created a program that puts you in control of your education and career sapiente, quia ab commodi veniam. Reiciendis neque dignissimos voluptatem modi est at! Architecto deleniti sa',
                    image: '/testimonial-2.jpg'
                },
                {
                    name: 'Balkis Taiwo ',
                    occupation: 'Front-End Dev.',
                    speech: 'Reflecting on my time at Dervac Hub, I am grateful for the experience I gained as an IT personnel and web developer intern. The combination of troubleshooting IT issues and crafting innovative web solutions has equipped me with a versatile skill set that I am eager to leverage in my future career endeavors.',
                    image: '/Balkis.jpg'
                },
                {
                    name: 'Yusuf Olatunji',
                    occupation: 'Front-End Dev.',
                    speech: "I would like to use this medium to thank DERVAC for their wonderful contribution. I just wanted to share a quick note and let you know that  DERVAC is the best place to learn.   I'm so glad that I am part of the team. I always thought that Web Dev is hard to learn but you prove me wrong. Thanks, Jaza kumu lahu khairan.",
                    image: '/agba.jpg'
                },
                {
                    name: 'Ibrahim Akande',
                    occupation: "Front-End Dev.",
                    speech: "I had the privilege of learning and growing at Dervac Global Services Limited, and I must say, it was a truly transformative experience. The team's dedication to mentoring and guidance helped me develop my coding skills from scratch. I am forever grateful for the opportunity to have been a part of this amazing team and I highly recommend Dervac Global Services Limited to anyone looking to kickstart their coding journey!",
                    image: '',
                },
                {
                    name: "Sulaiman Dosu",
                    occupation: "Front-End Dev.",
                    speech: "I've had an incredible experience in the frontend program at DERVAC GLOBAL SERVICES LIMITED! The curriculum was comprehensive and challenging, but the support from the instructors and peers was top-notch. I loved how hands-on the projects were, and how quickly I was able to apply what I learned to real-world scenarios. The program not only taught me valuable skills, but also gave me the confidence to pursue a career in tech. I'm so grateful for the opportunity and would highly recommend it to anyone looking to start or advance their journey in frontend development. Thank you for an amazing experience!",
                    image: "/dosu.jpg",
                },
                {
                    name: "Adebayo Nofisat",
                    occupation: "Front-End Dev.",
                    speech: "Dervac Global Services Limited ignited my coding journey! With their expert guidance and supportive environment, I gained the skills and confidence to succeed. I'm forever grateful for the opportunity to have learned and grown with this amazing team!",
                    image: ""
                },
                {
                    name: "Stanley Meruo",
                    occupation: "Front-End Dev.",
                    speech: "I would like to express my gratitude for this career journey I took. It has been an enriching experience, and I have gained a substantial amount of knowledge and skills in frontend development at DERVAC GLOBAL SERVICES, significantly improved my skills and confidence in frontend development, and I feel well-prepared to tackle future projects.",
                    image: "/stanley.jpg"
                },
                {
                    name: "AbdWaris Jimoh",
                    occupation: "Front-End Dev.",
                    speech: "I'm so grateful to Dervac for helping me achieve my dream. I was a complete beginner, but they broke everything down in a way that made sense to me. Their teaching style is clear, concise, and patient. They encouraged me to keep practicing, even when it got tough. And now, I'm proud to say that I'm a frontend developer! Dervac's guidance and support have opened up new career opportunities for me. I can't recommend them enough. If you want to learn coding, look no further than Dervac. They're the best!",
                    image: ""
                },
                {
                    name: "Lawal Maryam",
                    occupation: "Front-End Dev.",
                    speech: "I'm thrilled to be a part of the Dervac Global Services team! The company's commitment to excellence, innovation, and customer satisfaction is inspiring. The supportive work environment, opportunities for growth, and collaborative culture have helped me grow both professionally and personally. I'm impressed by the company's dedication to delivering top-notch services and exceeding client expectations. Dervac Global Services truly cares about its employees and clients, making it a fantastic place to work and build a career. I feel proud to be a part of this talented team!",
                    image: ""
                },
                {
                    name: "Mukhtar Lawal",
                    occupation: "Front-End Dev.",
                    speech: "we  give thank to Almighty ALLAH may the peace and bless be upon the noble prophet rosullahi s.a.w , that let this journey to be a successful one for us in this tech era, by unlocking our potential @dervacHUB to acquire a skill of being a frontend developer in the cohort 4 fellowship program we really appreciate the management  with their effort, consistency, guide and the experience  @dervacHUB  by giving us the opportunity to acquire a skill and achieve our goal. may Almighty ALLAH reward and appreciate you for all you effort ameen.",
                    image: ""
                },
            ],
            showSummer: false,
            showWeekend: false,
            showRemote: false,
            showWeekday: false,
            showExecutive: false,
            showAnswer: false,
            learnMoreBgBlue: true,
            changeHireColor: false,
            changeApplyNowColor: false,
            drop: false,
            dropCollaborateOptions: false,
            team: [
                { 
                    id: 1,
                    name: 'Muhsin Ishaq Anjorin',
                    based: "CIO / Team Lead", 
                    linkedIn: 'https://www.linkedin.com/in/anjorin4us/',
                    website: 'https://anjorin.net/',
                    twitter: 'https://twitter.com/anjorin4us',
                    imageUrl: 'src/assets/anjorin.JPG'
                },
                { 
                    id: 2,
                    name: 'Ibrahim Opeyemi',
                    based: "Enterprise / IT Support", 
                    linkedIn: 'https://www.linkedin.com/in/ibrahim-akorede-53a53527b/',
                    website: '../assets/ib.jpg',
                    twitter: '#',
                    imageUrl: '../assets/ib.jpg',
                },
                { 
                    id: 3,
                    name: 'AbdulQoyum Aliyu',
                    based: "Software Developer", 
                    linkedIn: 'https://www.linkedin.com/in/abdulqoyum-aliyu-ba6355183/', 
                    website: 'https://www.linkedin.com/in/abdulqoyum-aliyu-ba6355183/', 
                    twitter: 'https://www.linkedin.com/in/abdulqoyum-aliyu-ba6355183/', 
                    imageUrl: '../assets/aliy.png', 
                },
                { 
                    id: 4,
                    name: 'Dehinde Fowora',
                    based: "Systems Infrastructure", 
                    linkedIn: 'https://www.linkedin.com/in/dehinde-nasrudeen-fowora-665072b5/', 
                    website: '../assets/dehinde.jpg', 
                    twitter: '#', 
                    imageUrl: '../assets/dehinde.jpg', 
                },
                { 
                    id: 5,
                    name: 'Sikiru Jimoh',
                    based: "Systems Infrastructure", 
                    linkedIn: '../assets/dehinde.jpg', 
                    website: '../assets/dehinde.jpg', 
                    twitter: '#', 
                    imageUrl: '../assets/dehinde.jpg', 
                },
                { 
                    id: 6,
                    name: 'Lawal-fowora Khadijah',
                    based: "UI/UX Designer", 
                    linkedIn: 'https://www.linkedin.com/in/khadijah-lawal-fowora-b5244160/', 
                    website: '../assets/dehinde.jpg', 
                    twitter: '#', 
                    imageUrl: '../assets/dehinde.jpg', 
                },
                { 
                    id: 7,
                    name: 'Maruf Ajagunna',
                    based: "Software Developer", 
                    linkedIn: 'https://www.linkedin.com/in/marufdeen-ajagunna-a634a4113/', 
                    website: '../assets/ajagunna.jpg', 
                    twitter: 'https://twitter.com/MarufdeenB', 
                    imageUrl: '../assets/ajagunna.jpg', 
                },
                { 
                    id: 8,
                    name: 'Hassan Akeredolu',
                    based: "Technical Officer", 
                    linkedIn: 'https://www.linkedin.com/in/akeredolu-hassan-8a799850/', 
                    website: '../assets/hassan.jpg', 
                    twitter: 'https://twitter.com/HassanAkeredolu', 
                    imageUrl: '../assets/hassan.jpg', 
                },
                { 
                    id: 9,
                    name: 'Sanni Hammed',
                    based: "Front-End Developer", 
                    linkedIn: 'https://www.linkedin.com/in/hammed-sanni-b27765236/',
                    website: 'https://abdulhameedi.github.io/portfolio_june_23/',
                    twitter: 'https://twitter.com/HammedSanni5',
                    imageUrl: '../assets/hammed.png'
                },               
                { 
                    id: 10,
                    name: 'Luqmon AbdurRahman',
                    based: "Front-End Developer", 
                    linkedIn: 'https://www.linkedin.com/in/surecoders/', 
                    website: '../assets/ajagunna.jpg', 
                    twitter: 'https://twitter.com/MarufdeenB', 
                    imageUrl: '../assets/tijani.jpg', 
                },
                { 

                    id: 11,
                    name: 'Fawwaz Makinde',
                    based: "Front-End Developer", 
                    linkedIn: '../assets/fawaz.jpg', 
                    website: '../assets/fawaz.jpg', 
                    twitter: '../assets/fawaz.jpg', 
                    imageUrl: '../assets/fawaz.jpg', 
                },
                { 
                    id: 12,
                    name: 'Yunus Qudus',
                    based: "Software Engineer", 
                    linkedIn: 'https://www.linkedin.com/in/abdulqudus-yunus-2a1153151/', 
                    website: '#', 
                    twitter: '#', 
                    imageUrl: '../assets/yunusSanni.jpg', 
                },
                { 
                    id: 13,
                    name: 'Lateef Kazeem',
                    based: "IT associate", 
                    linkedIn: '#', 
                    website: '#', 
                    twitter: '#', 
                    imageUrl: '../assets/yunusSanni.jpg', 
                },
            ],
            fellows: [
                    { 
                        id: 1,
                        name: 'Olatunji Yusuf',
                        based: "Front-End Developer", 
                        website: '../assets/agba.jpg', 
                        linkedIn: '../assets/agba.jpg', 
                        twitter: '../assets/agba.jpg', 
                        imageUrl: '../assets/agba.jpg',
                        year: 2023,
                    },
                    { 
                        id: 1,
                        name: 'Abdulrahman Luqman',
                        based: "Front-End Developer", 
                        website: '../assets/luqman.png', 
                        linkedIn: '../assets/luqman.png', 
                        twitter: 'https://twitter.com/luqmanola60', 
                        imageUrl: '../assets/luqman.png', 
                        year: 2023,
                    },
                    { 
                        id: 3,
                        name: 'Olawore Emmanuel',
                        based: "Front-End Developer", 
                        website: '../assets/emma.jpg', 
                        linkedIn: '../assets/emma.jpg', 
                        twitter: '../assets/emma.jpg', 
                        imageUrl: '../assets/emma.jpg', 
                        year: 2023,
                    },
                    { 
                        id: 4,
                        name: 'Balkis Taiwo',
                        based: "Front-End Developer", 
                        website: '../assets/balkis.jpg', 
                        linkedIn: '../assets/balkis.jpg', 
                        twitter: '../assets/balkis.jpg', 
                        imageUrl: '../assets/balkis.jpg', 
                        year: 2023,
                    },
                    { 
                        id: 5,
                        name: 'Adam Ayinde',
                        based: "Front-End Developer", 
                        website: '../assets/adam.jpg', 
                        linkedIn: '../assets/adam.jpg', 
                        twitter: '../assets/adam.jpg', 
                        imageUrl: '../assets/adam.jpg', 
                        year: 2022,
                    },
                    { 
                        id: 7,
                        name: 'Okeyale Zakariya',
                        based: "Front-End Developer", 
                        website: '../assets/zakariyya.jpg', 
                        linkedIn: '../assets/zakariyya.jpg', 
                        twitter: 'https://twitter.com/OkeyaleZ', 
                        imageUrl: '../assets/zakariyya.jpg', 
                        year: 2023,
                    },
                    { 
                        id: 8,
                        name: 'Abdulazeez Abdulganiy',
                        based: "Front-End Developer", 
                        website: '../assets/abdulaziz.jpg', 
                        linkedIn: '../assets/abdulaziz.jpg', 
                        twitter: '../assets/abdulaziz.jpg', 
                        imageUrl: '../assets/abdulaziz.jpg', 
                        year: 2023,
                    },
                    { 
                        id: 9,
                        name: 'Abdullah Abdulkareem',
                        based: "Front-End Developer", 
                        website: '../assets/emma.jpg', 
                        linkedIn: '../assets/emma.jpg', 
                        twitter: '../assets/emma.jpg', 
                        imageUrl: '../assets/emma.jpg', 
                        year: 2023,
                    },
                    { 
                        id: 10,
                        name: 'Olakunmi Abdulsalam',
                        based: "Front-End Developer", 
                        website: '../assets/olakunmi.jpg', 
                        linkedIn: '../assets/olakunmi.jpg', 
                        twitter: '../assets/olakunmi.jpg', 
                        imageUrl: '../assets/olakunmi.jpg', 
                        year: 2022,
                    },
                    { 
                        id: 11,
                        name: 'Sanni Hammed',
                        based: "Front-End Developer", 
                        linkeyouyoudIn: 'https://www.linkedin.com/in/hammed-sanni-b27765236/',
                        website: 'https://abdulhameedi.github.io/portfolio_june_23/',
                        twitter: 'https://twitter.com/HammedSanni5',
                        imageUrl: '../assets/hammed.png',
                        year: 2022,
                    },
                    { 
                        id: 12,
                        name: 'Esther Odutayo',
                        based: "Front-End Developer", 
                        linkedIn: 'https://www.linkedin.com/in/esther-odutayo-06a116274/', 
                        website: '../assets/esther.jpg', 
                        twitter: '../assets/esther.jpg', 
                        imageUrl: '../assets/esther.jpg', 
                        year: 2023,
                    },
                    { 
                        id: 13,
                        name: 'Fawwaz Makinde',
                        based: "Front-End Developer", 
                        linkedIn: '../assets/fawaz.jpg', 
                        website: '../assets/fawaz.jpg', 
                        twitter: '../assets/fawaz.jpg', 
                        imageUrl: '../assets/fawaz.jpg',
                        year: 2023, 
                    },
                    { 
                        id: 13,
                        name: 'Abdul-Roheem Aromire',
                        based: "Front-End Developer", 
                        linkedIn: '../assets/fawaz.jpg', 
                        website: '../assets/fawaz.jpg', 
                        twitter: '../assets/fawaz.jpg', 
                        imageUrl: '../assets/fawaz.jpg',
                        year: 2021, 
                    },
                    { 
                        id: 13,
                        name: 'Usman Zahradeen',
                        based: "Front-End Developer", 
                        linkedIn: '../assets/fawaz.jpg', 
                        website: '../assets/fawaz.jpg', 
                        twitter: '../assets/fawaz.jpg', 
                        imageUrl: '../assets/fawaz.jpg',
                        year: 2021, 
                    },
                    { 
                        id: 13,
                        name: 'Aransiola Abdulquadri',
                        based: "Front-End Developer", 
                        linkedIn: '../assets/fawaz.jpg', 
                        website: '../assets/fawaz.jpg', 
                        twitter: '../assets/fawaz.jpg', 
                        imageUrl: '../assets/fawaz.jpg',
                        year: 2021, 
                    },
                    { 
                        id: 13,
                        name: 'Kosoko Quam',
                        based: "Front-End Developer", 
                        linkedIn: '../assets/fawaz.jpg', 
                        website: '../assets/fawaz.jpg', 
                        twitter: '../assets/fawaz.jpg', 
                        imageUrl: '../assets/fawaz.jpg',
                        year: 2021, 
                    },
                    { 
                        id: 13,
                        name: 'AbdulRasheed Sirajudeen',
                        based: "Front-End Developer", 
                        linkedIn: '../assets/fawaz.jpg', 
                        website: '../assets/fawaz.jpg', 
                        twitter: '../assets/fawaz.jpg', 
                        imageUrl: '../assets/fawaz.jpg',
                        year: 2022, 
                    },
                
            ],
            showAnswerInMainPage: false,
            onPage: true,
            nextPage: true,
            nextAfterPage: true,
            Apply: 1,
            ApplyPageShow: true,
            disableScroll: false,
            showButton: false,
            testimonialsPage: [
                {
                    name: 'Okeyale Zakariyyah',
                    occupation: 'Front-End Dev.',
                    testimony: 'I had an incredible experience at Dervac Hub!  The comprehensive curriculum, hands-on projects and knowledgeable instructors made learning complex concepts a breeze. The practical approach to teaching ensured that I not only understood the theory but could also apply it in real-world scenarios. Am excited about the opportunities ahead. I highly recommend Dervac Hub to anyone looking to kickstart or enhance their career in technology.',
                    image: '../assets/others/alfa-zakariyyah.jpg'
                },
                {
                    name: 'Sanni AbdHameed',
                    occupation: 'Front-End Dev.',
                    testimony: "DervacHub has been a beacon of guidance in my journey toward becoming a proficient developer. The curriculum, thoughtfully curated with industry demands in mind, allowed me to grasp intricate concepts effortlessly. What truly stood out was their emphasis on practical application – from coding challenges to collaborative projects – fostering skills that translate directly into the real world. DervacHub's dedication to my growth and success has not only shaped my technical abilities but also instilled in me a profound confidence to innovate and create. I am immensely grateful for the enriching experience and wholeheartedly recommend DervacHub to aspiring developers.",
                    image: '../assets/testimonial-2.jpg'
                },
                {
                    name: 'AbdurRasheed',
                    occupation: 'Front-End Dev.',
                    testimony: 'Dervac Global Services;it was a great experience having my SIWES with you, you are the real definition of industrial training as I had the opportunity to get practical experience of what Computet Science entails, I got my bearing as student of computer science at Dervac and also was able to know my potentials as Dervac gave me the opportunity to explore alot of fields in IT.One of the greatest potential of Dervac is  "follow-up",she made herself always available to support my growth.Thanks so much Dervac',
                    image: '../assets/others/abdrrasheed.jpg'
                },
                {
                    name: 'Taiwo Balkis',
                    occupation: 'Front-End Dev.',
                    testimony: 'During my stay at Dervac Hub as a software developer and an IT personnel, I had the privilege of being part of an innovative and forward-thinking team. The office buzzed with creativity and collaboration, making each day an exciting journey. I learned to seamlessly integrate aesthetics with functionality, resulting in user-friendly. Regular stand-up meetings ensured that everyone was aligned, and I appreciated the camaraderie and support within the team. Code reviews were a valuable opportunity for learning and growth, and I eagerly learned from my peers.  ',
                    image: '../assets/others/Balkis.jpg',
                },
                {
                    name: 'Aadam',
                    occupation: 'Front-End Dev.',
                    testimony: "Dear DERVAC, I'd like to express my gratitude for your supervision and guidance during my internship. My experience was very valuable, and I've gained so much insight into the world of ICT. I enjoyed working and collaborating with you, my fellow interns back then and now. I was delighted to be part of such an amazing and organized INFORMATION TECHNOLOGY organization.Thanks again for this incredible internship, and I wish you and the [DERVAC TEAM] all the best.",
                    image: '../assets/others/Oogee.jpg',
                },
                {
                    name: 'AbdSalaam',
                    occupation: 'Front-End Dev.',
                    testimony: 'My internship at Dervac hub was truly an invaluable and transformative experience. Throughout my time there, I had the privilege of gaining valuable insights and skills in various areas, including team management, which taught me how to effectively collaborate and lead in a professional setting. Additionally, the exposure to different challenging projects allowed me to refine my problem-solving abilities and think creatively to overcome obstacles. One of the standout aspects of my internship was the emphasis on computer literacy.',
                    image: '../assets/others/abdSalam.jpg',
                },
                {
                    name: 'Okeyale Zakariyyah',
                    occupation: 'Front-End Dev.',
                    testimony: 'I had an incredible experience at Dervac Hub!  The comprehensive curriculum, hands-on projects and knowledgeable instructors made learning complex concepts a breeze. The practical approach to teaching ensured that I not only understood the theory but could also apply it in real-world scenarios. The engaging learning environment created a positive atmosphere that fostered growth and confidence. Thanks to this training. Am excited about the opportunities ahead. I highly recommend Dervac Hub to anyone looking to kickstart or enhance their career in technology',
                    image: '../assets/others/alfa-Zakariyyah',
                },
                {
                    name: 'Yusuf Olatunji',
                    occupation: 'Front-End Dev.',
                    testimony: "I would like to use this medium to thank DERVAC for their wonderful contribution. I just wanted to share a quick note and let you know that  DERVAC is the best place to learn.   I'm so glad that I am part of the team. I always thought that Web Dev is hard to learn but you prove me wrong.Thanks, Jaza kumu lahu khairan.",
                    image: '../assets/others/agba.jpg',
                },
                {
                    name: "AbdGaniy AbdA'zeez",
                    occupation: 'Front-End Dev.',
                    testimony: "I am taking this opportunity to express my heartfelt gratitude to DervacHub. They have taken me from being a computer fundamentalist to a skilled front-End developer in just six months. While it demanded dedicated hard work and relentless effort, the results have been truly rewarding. The transformation and growth I've experienced are a testament to the value and commitment that DervacHub brings to its programs." ,
                    image: '../assets/abdulaziz.jpg',
                },
                {
                    name: 'Luqman AbdurRahman',
                    occupation: 'Front-End Dev.',
                    testimony: "Joining DervacHub was a pivotal moment in my career journey. The guidance and mentorship I received there were instrumental in shaping me into a competent and confident developer. The hands-on approach to learning, coupled with real-world projects, enabled me to apply theoretical concepts to practical situations.Thanks to DervacHub, I now possess the skills and knowledge needed to thrive in the ever-evolving tech industry.",
                    image: '../assets/luqman.png'
                },
                {
                    name: 'Makinde Fawwaz',
                    occupation: 'Front-End Dev.',
                    testimony: 'My experience with DervacHub has been nothing short of phenomenal. Enrolling in their program was a game-changer for me. The curriculum is expertly designed, covering a wide spectrum of topics crucial for a well-rounded developer. From coding fundamentals to advanced techniques, I was amazed at how seamlessly they guided me through the learning journey.        one of the qualities that truly sets DervacHub apart is their incredible support system. The our tutor is not only knowledgeable but also incredibly approachable. Whenever I hit a roadblock or needed clarification, he is right there to guide me, making the learning process smoother and more enjoyable.',
                    image: '../assets/fawaz.jpg',
                },
                {
                    name: 'Esther',
                    occupation: 'Front-End Dev.',
                    testimony: " DervacHub doesn't just teach you to code; they empower you to think critically and solve complex challenges. I am immensely grateful for the transformative experience and highly recommend DervacHub to anyone aspiring to excel in the world of technology. They exceeded all my expectations in my pursuit of becoming a proficient developer. The structured curriculum, coupled with their emphasis on hands-on learning, accelerated my growth exponentially. ",
                    image: '../assets/esther.jpg',
                },
                {
                    name: 'Olawore Emmanuel',
                    occupation: 'Front-End Dev.',
                    testimony: "Enrolling in DervacHub was a decision I'll forever cherish. Their comprehensive program transformed my passion for technology into tangible skills. The practical projects and real-world simulations equipped me to navigate the dynamic landscape of development. I'm immensely grateful for the opportunity and confident in recommending DervacHub to anyone seeking a transformative learning experience.",
                    image: '../assets/emma.jpg'
                }
            ]
        })
    })()
}
